### ISSUE TITLE
The retry on ranking panel is fucked up.

### ISSUE THREAD

**Issue by yousef157** [eclipsedteam/HiTech#4]
![image](https://user-images.githubusercontent.com/48018938/62078044-bc748900-b25c-11e9-8cce-4cbd0a84ec92.png)

**Comment by Tanza3D** [comment]
This will be fixed with the coming of the new rankingpanel and pausemenu.

**Comment by yousef157** [comment]
> This will be fixed with the coming of the new rankingpanel and pausemenu.

Ok, but don't release the first release without a new pausemenu.

**Comment by Tanza3D** [comment]
weeks to come

**Comment by yousef157** [comment]
2 months to come
